<?php
$fields = $this->getFields();
$useIframe = Mage::getStoreConfig('payment/multon_everypay/connection_type') || isset($fields['cc_token']);

if ($useIframe)
{
	?>
	<iframe id="iframe-payment-container" name="iframe-payment-container" width="460" height="400"
			style="border: none; <?php if (isset($fields['cc_token'])) echo 'display: none'; ?>"
	></iframe>
	<div id="iframe-messages" <?php if (!isset($fields['cc_token'])) echo 'style="display: none"'; ?>>
		<div class="page-title">
			<h1 id="message_title"></h1>
		</div>
		<p id="message_error"></p>
		<p id="message_action"></p>
		<p id="message_contact"></p>
	</div>
	<div id="link-to-orders" style="display: none">

<?php
	$order = $this->getOrder();
	$isVisible = !in_array($order->getState(), Mage::getSingleton('sales/order_config')->getInvisibleOnFrontStates());

	if (Mage::getSingleton('customer/session')->isLoggedIn() && $isVisible)
	{
?>
    <p><?php echo $this->__('Your order # is: %s.', sprintf('<a href="%s">%s</a>', $this->escapeHtml($this->getUrl('sales/order/view/', array('order_id' => $order->getId()))), $this->escapeHtml($order->getIncrementId()))) ?></p>
<?php  } else  { ?>
    <p><?php echo $this->__('Your order # is: %s.', $this->escapeHtml($order->getIncrementId())) ?></p>
<?php } ?>

		<div class="buttons-set">
			<button type="button" class="button" title="<?php echo $this->__('My previous orders') ?>" onclick="window.location='<?php echo $this->getUrl('sales/order/history') ?>'"><span><span><?php echo $this->__('My previous orders') ?></span></span></button>
		</div>
	</div>
<?php } ?>

<div class="payment_everyay_container payment_method_everypay">
	<?php echo $this->getChildHtml('everypay_everypay_description') ?>
    <form
	<?php if (!$useIframe)
		{
		?>
			id="GatewayForm"  target="_top"
		<?php } else
		{
			?>
			id="iframe_form" style="display: none" target="iframe-payment-container"
		<?php } ?>
		name="everypay" action="<?php echo $this->getGatewayUrl() ?>transactions/" method="POST">
        <input type="image" src="<?php echo $this->getMethodLogoUrl(); ?>" onclick="this.form.submit()" class="payment-gateway-logo everypay_logo"/>
		<?php foreach ($fields as $key => $value)
		{ ?>
			<input type="hidden" name="<?php echo $key ?>" value="<?php echo $value ?>"/>
	<?php } ?>
    </form>
	<?php
	if (!$useIframe)
		echo $this->getQuickRedirectScript();
	else
	{
		?>
		<script>
			window.onload = function () {
				document.getElementById("iframe_form").submit();
			};

			var shrinked_iframe_data;
			var iframe = jQuery('#iframe-payment-container'); // iframe selector should be used

			var shrinkIframe = function (iframe, iframe_data) {
				iframe.css(iframe_data);
				jQuery("#dimmed_background_box").remove();
			};
			var expandIframe = function () {
				var iframe_data = {
					position: iframe.attr("position") || "static",
					top: iframe.position().top,
					left: iframe.position().left,
					width: iframe.width(),
					height: iframe.height(),
					zIndex: iframe.attr("zIndex"),
					marginLeft: iframe.attr("marginLeft"),
					marginRight: iframe.attr("marginRight")
				};

				jQuery('body').append("<div id='dimmed_background_box'></div>");
				jQuery('#dimmed_background_box').css({height: '100%', width: '100%', position: 'fixed', top: 0, left: 0, zIndex: 9998, backgroundColor: '#000000', opacity: 0.5});

				var window_height = jQuery(window).height();
				var window_width = jQuery(window).width();

				if (window_width < 960) {
					iframe.css({height: window_height, width: window_width, top: 0});
				} else {
					iframe.css({height: 640, width: 960, top: (window_height - 640) / 2, left: (window_width - 960) / 2});
				}
				iframe.css({position: 'fixed', zIndex: 9999, margin: 'auto'});
				return iframe_data;
			};

			window.addEventListener('message', function (event) {
				if (event.origin.concat("/") !== "<?php echo $this->getGatewayUrl() ?>") {
					return;
				}

				var message = JSON.parse(event.data);
				/*
				 1. An "expand" message is sent from the iframe page when 3D secure page is going to be displayed.
				 The size of the iframe should be adjusted to hold 3D secure page
				 2. A "shrink" message is sent from the iframe page when a user has provided authorisation details on the 3D secure page.
				 The size of the iframe should be set to the initial values
				 */
				if (message.resize_iframe === "expand") {
					shrinked_iframe_data = expandIframe(iframe);
				} else if (message.resize_iframe === "shrink") {
					shrinkIframe(iframe, shrinked_iframe_data);
				}

	// It receives a message from the iframe about transaction's result. Possible states: completed, failed.
				if (message.transaction_result) {
					if (message.transaction_result === "completed")
					{
						window.location="<?php echo Mage::getUrl('checkout/onepage/success'); ?>";
					} else
					{
						jQuery('#message_title').append(message.message_title);
						jQuery('#message_error').append(message.message_error);
						jQuery('#message_action').append(message.message_action);
						jQuery('#message_contact').append(message.message_contact);
						jQuery('#link-to-orders').show() // link to order history
					}
				}
			}, false);

		</script>
<?php } ?>
</div>