<?php
echo $this->getMessagesBlock()->getGroupedHtml();
$tokens = $this->getTokens();
?>
<div class="page-title">
    <h1><?php echo $this->__('Saved cards') ?></h1>
</div>
<?php
echo $this->getPagerHtml();
if($tokens->getSize()) {
?>
<table class="data-table" id="my-tokens-table">
    <thead>
        <tr>
            <th><?php echo $this->__('Card type') ?></th>
            <th><?php echo $this->__('Card number') ?></th>
            <th><?php echo $this->__('Expires') ?></th>
            <th>&nbsp;</th>
            <th>&nbsp;</th>
        </tr>
    </thead>
    <tbody>
        <?php
		$_odd = '';
        foreach ($tokens as $token)
		{
			$expired = false;
			if (
					($token->getCcYear() < date('Y')) ||
					(
							($token->getCcYear() == date('Y')) &&
							($token->getCcMonth() < date('m'))
					)
				)
				$expired = true;
		?>
        <tr>
            <td><img src="<?php echo $this->getSkinUrl('images/multon/everypay/'.$token->getCcType().'.png'); ?>" alt="<?php echo $token->getCcType() ?>" height="25px" /></td>
            <td <?php if ($expired) echo 'style="color: red"'; ?> >&nbsp;****&nbsp;****&nbsp;****&nbsp;<?php echo $token->getCcLastFourDigits() ?></td>
            <td <?php if ($expired) echo 'style="color: red"'; ?> ><?php printf('%02d', $token->getCcMonth()) ?>/<?php echo $token->getCcYear() ?></td>
            <td class="a-center">
				<?php if ($token->getIsDefault()) {
					echo $this->__('Default');
				 } else { ?>
				<span class="nobr">
					<a href="<?php echo $this->getUrl('everypay/token/setDefault') ?>token/<?php echo $token->getId() ?>"><?php echo $this->__('Set as default') ?></a>
				</span>
				<?php } ?>
            </td>
            <td class="a-center">
				<span class="nobr">
					<a href="#" onclick="return deleteToken('<?php echo $token->getId() ?>');" class="red-link"><?php echo $this->__('Delete') ?></a>
				</span>
            </td>
        </tr>
		<?php } ?>
    </tbody>
</table>
<script type="text/javascript">
	decorateTable('my-tokens-table');

    function deleteToken(tokenId) {
        if (confirm('<?php echo $this->__('Are you sure you want to delete this token?') ?>'))
		{
            window.location='<?php echo $this->getUrl('everypay/token/delete') ?>token/'+tokenId;
        }
        return false;
    }
</script>
<?php
	echo $this->getPagerHtml();
} else { ?>
    <p><?php echo $this->__('You have no saved cards.'); ?></p>
<?php } ?>
